services:
  web:
    build:
      context: .
    container_name: ig_web
    ports:
      - "8000:8000"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: "postgres:14"
    container_name: ig_db
    ports:
      - "5432:${DB_PORT:-5432}"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-instagrammers}
      POSTGRES_PORT: ${DB_PORT:-5432}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
